### PR TITLE
Adds new Expansion style

### PR DESCRIPTION
**Pull request by robertogvieira**
- Adds new `ExpansionStyle`: **`singlePerSection`**;
- Adapts existing code to handle new style.

**Notes**: 
1. This PR is based on PR #53 (where the initial idea for this new case came from);
2. Demo (_ExpandableCellDemo_) wasn't updated with a new button to test this new expansion style behaviour to avoid "overcrowding" the navigation bar with buttons. 
TL;DR: it can be easily tested by simply replacing the style (`ExpansionStyle.single`) currently set in method `ViewController.expandSingleButtonClicked(_:)` with `ExpansionStyle.singlePerSection`.

### CODE REVIEW

**Comment by pikaboo** [comment]
You need to
```   if self.expansionStyle == .single {
                    closeAll()
                }```
After you have gotten the index of the cell with
``` if let cell = self.cellForRow(at: indexPath) {```
and before you do this:
```   if let correctIndexPath = self.indexPath(for: cell) {```

because after all the cells close, the index of the cell at hand is not the index it was when it was open.
The same goes for the condition if the style is singlePerSection

**Comment by pikaboo** [comment]
could you update documentation please ?

**Comment by pikaboo** [comment]
@younatics Can you release new pod version? I'm not able to

**Comment by younatics** [comment]
@pikaboo  I will do :)

**Pull request merged**
