### PR TITLE
Expand cells in different sections

### PR DESCRIPTION
**Pull request by robertogvieira**
- Enables the expansion of cells from different sections, which was a limitation so far.

### CODE REVIEW

**Comment by robertogvieira** [comment]
hey @pikaboo. You're right, thanks for the feedback 👍 
I was thinking if, instead of just considering the `ExpansionStyle.single` case, it would make sense to add another `ExpansionStyle` case: "single per section", which was basically the behaviour before my last commit: only one row can be expanded **per section**. 
Do you see that as a possible use case?

**Comment by pikaboo** [comment]
@robertogvieira I think it could be a use case

**Comment by pikaboo** [comment]
@younatics can you please push the pod to the trunk for the recent tag i created ?

**Comment by robertogvieira** [comment]
@pikaboo commit 6e7e264 fixes the issue you pointed out.
Created new PR #54 for the new expansion style `ExpansionStyle.singlePerSection`, since it's out of the scope of the issue addressed in this PR, although it is based on this PR.

//cc @younatics

**Pull request merged**
